name: Auto Report

on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 10,21 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install libcairo2-dev
        gcc image/image.c -lcairo -o image/image
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      env:
        CONFIG: ${{ secrets.config }}
      run: |
        echo "$CONFIG" > ./config.ini
        python3 run.py
